import jsPDF from 'jspdf'

export async function generateInvoicePDF(invoice, customer, settings) {
  const doc = new jsPDF()
  const primaryColour = settings?.primary_colour || '#2563EB'
  
  // Header with logo
  if (settings?.logo_url) {
    try {
      doc.addImage(settings.logo_url, 'PNG', 20, 15, 40, 30)
    } catch (e) {
      console.log('Logo error:', e)
    }
  }
  
  // Company name (or default ClearRoute)
  doc.setFontSize(20)
  doc.setTextColor(primaryColour)
  doc.text(settings?.company_name || 'ClearRoute', 70, 30)
  
  // Company address
  doc.setFontSize(8)
  doc.setTextColor(100)
  const addressParts = [
    settings?.address_line_1,
    settings?.address_line_2,
    settings?.city,
    settings?.postcode,
    settings?.country
  ].filter(Boolean)
  
  if (addressParts.length > 0) {
    let y = 38
    addressParts.forEach(line => {
      doc.text(line, 70, y)
      y += 4
    })
  }
  
  // Invoice title
  doc.setFontSize(24)
  doc.setTextColor(0)
  doc.text('INVOICE', 190, 30, { align: 'right' })
  doc.setFontSize(12)
  doc.text(invoice.invoice_number, 190, 40, { align: 'right' })
  
  // Divider
  doc.setDrawColor(200)
  doc.line(20, 55, 190, 55)
  
  // Bill To
  doc.setFontSize(10)
  doc.setTextColor(100)
  doc.text('Bill To:', 20, 65)
  doc.setTextColor(0)
  doc.setFontSize(11)
  doc.text(customer?.name || 'Customer', 20, 72)
  if (customer?.address_line_1) {
    doc.setFontSize(9)
    doc.text(customer.address_line_1, 20, 79)
    if (customer.city) doc.text(`${customer.city} ${customer.postcode || ''}`, 20, 85)
    if (customer.email) doc.text(customer.email, 20, 91)
  }
  
  // Invoice Details
  doc.setFontSize(9)
  doc.setTextColor(100)
  doc.text('Issue Date:', 140, 65)
  doc.text('Due Date:', 140, 72)
  doc.text('Payment Terms:', 140, 79)
  
  doc.setTextColor(0)
  doc.text(invoice.issue_date || '', 170, 65)
  doc.text(invoice.due_date || '', 170, 72)
  doc.text(invoice.payment_terms || 'Net 30', 170, 79)
  
  // Line Items Table Header
  let tableY = 105
  doc.setFillColor(primaryColour)
  doc.rect(20, tableY, 170, 8, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(9)
  doc.text('Description', 22, tableY + 5.5)
  doc.text('Qty', 110, tableY + 5.5)
  doc.text('Rate', 130, tableY + 5.5)
  doc.text('Amount', 160, tableY + 5.5)
  
  // Line Items
  tableY += 12
  const items = invoice.items || []
  doc.setTextColor(0)
  
  items.forEach((item, i) => {
    if (i % 2 === 0) {
      doc.setFillColor(245)
      doc.rect(20, tableY - 4, 170, 8, 'F')
    }
    doc.text(item.description?.substring(0, 35) || '', 22, tableY + 1)
    doc.text(String(item.quantity || 1), 115, tableY + 1)
    doc.text(`£${Number(item.unit_price || 0).toFixed(2)}`, 130, tableY + 1)
    doc.text(`£${Number(item.line_total || 0).toFixed(2)}`, 160, tableY + 1)
    tableY += 8
  })
  
  // Totals
  tableY += 10
  doc.line(20, tableY, 190, tableY)
  tableY += 8
  
  doc.setTextColor(100)
  doc.text('Subtotal:', 130, tableY)
  doc.setTextColor(0)
  doc.text(`£${Number(invoice.subtotal || 0).toFixed(2)}`, 160, tableY)
  
  tableY += 8
  doc.setTextColor(100)
  doc.text(`VAT (${(invoice.vat_rate || 0.20) * 100}%):`, 130, tableY)
  doc.setTextColor(0)
  doc.text(`£${Number(invoice.vat_amount || 0).toFixed(2)}`, 160, tableY)
  
  tableY += 10
  doc.setFontSize(12)
  doc.setTextColor(primaryColour)
  doc.text('Total:', 130, tableY)
  doc.text(`£${Number(invoice.total || 0).toFixed(2)}`, 160, tableY)
  
  // Footer
  doc.setFontSize(8)
  doc.setTextColor(150)
  doc.text(`VAT Registered: ${settings?.vat_number || 'GB000000000'}`, 20, 270)
  doc.text(`Generated by ClearRoute`, 190, 270, { align: 'right' })
  
  return doc
}